import {test,expect} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import type {Result} from '../../src/ui/data.ts';
declare global {interface Window {latestResult:Result}}
const fixture=Buffer.concat(['900000001','900000004','900000016','900000017','900000008','900000013','900000015','900000010'].map(f=>Buffer.concat([fs.readFileSync('tests/fixtures/'+f+'.txt'),Buffer.from('\n')])));
test.beforeEach(async({page})=>{await page.addInitScript(()=>{const Native=window.Worker;window.Worker=class extends Native {constructor(url:string|URL,options?:WorkerOptions){super(url,options);this.addEventListener('message',e=>{if(e.data.type==='result')window.latestResult=e.data.payload.result;});}};});});
test('same source update, invalid persisted selections, conflicts, other filters and drag/drop',async({page})=>{
 await page.goto('/');await page.evaluate(()=>localStorage.setItem('coinpoker.ui.v1',JSON.stringify({unit:'₮',lines:[true,true,true,true],tab:'Overview',orders:{Days:[],Months:[],Limits:[],Positions:[]},filters:{period:'All Time',from:'',to:'',month:'',limits:['9999'],positions:['missing'],tables:['missing'],players:'9',game:'',splash:''}})));await page.reload();
 async function load(name:string,buffer:Buffer){const prior=await page.evaluate(()=>window.latestResult?.database.importedAt);await page.getByLabel('Select CoinPoker file').setInputFiles({name,mimeType:'text/plain',buffer});await expect.poll(()=>page.evaluate(()=>window.latestResult?.database.importedAt),{timeout:90000}).not.toBe(prior);await expect(page.getByRole('button',{name:'Cancel import'})).toHaveCount(0,{timeout:90000});await expect(page.getByTestId('card-hands')).toBeVisible();}
 await load('same.txt',fixture);await expect.poll(()=>page.evaluate(()=>window.latestResult.summary.hands)).toBe(8);expect(await page.getByLabel('Limit',{exact:true}).evaluate((s:HTMLSelectElement)=>s.selectedOptions.length)).toBe(0);const net=await page.getByTestId('card-net').innerText();await load('same.txt',fixture);expect(await page.getByTestId('card-net').innerText()).toBe(net);await page.locator('.diagnostics summary').click();await expect(page.getByText('Duplicates: 0 · Conflicts: 0')).toBeVisible();
 await load('conflicts.txt',Buffer.concat([fixture,Buffer.from('\n'),Buffer.from(fixture.toString().replace('Game ended:','\nGame ended:'))]));await expect(page.getByText('Duplicates: 7 · Conflicts: 1')).toBeVisible();
 await page.getByLabel('Game Type').selectOption('BombPot');await expect(page.getByTestId('card-vpip')).toContainText('—');await page.getByRole('button',{name:'Clear filters'}).click();await page.getByLabel('Players',{exact:true}).selectOption({index:1});await expect.poll(()=>page.evaluate(()=>window.latestResult.summary.hands)).toBeLessThan(8);await page.getByRole('button',{name:'Clear filters'}).click();await page.getByLabel('Splash',{exact:true}).selectOption('any');await expect.poll(()=>page.evaluate(()=>window.latestResult.summary.splashEvents)).toBeGreaterThan(0);await page.getByRole('button',{name:'Clear filters'}).click();await page.getByText('Tables',{exact:true}).click();await page.getByLabel('Table',{exact:true}).selectOption({index:0});await expect.poll(()=>page.evaluate(()=>window.latestResult.summary.hands)).toBeLessThan(8);
 const sameUniverse=await page.evaluate(()=>{const r=window.latestResult;return Object.values(r.rows).every(rows=>rows.reduce((n,v)=>n+v.summary.hands,0)===r.summary.hands&&rows.reduce((n,v)=>n+v.summary.net,0n)===r.summary.net)&&(!r.points.length||Math.abs(r.points.at(-1)!.currency[0]!-Number(r.summary.net)/100)<1e-8);});expect(sameUniverse).toBe(true);
 await page.getByRole('button',{name:'Clear filters'}).click();await page.evaluate(text=>{const dt=new DataTransfer();dt.items.add(new File([text],'dropped.txt',{type:'text/plain'}));document.querySelector('main')!.dispatchEvent(new DragEvent('drop',{dataTransfer:dt,bubbles:true,cancelable:true}));},fixture.toString());await expect(page.getByText('dropped.txt',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Cancel import'})).toHaveCount(0,{timeout:90000});
});
test('local import, filters, units, tables, preferences, diagnostics and recovery',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.getByText('Your file stays on this device.')).toBeVisible();
 await page.getByLabel('Select CoinPoker file').setInputFiles({name:'fixtures.txt',mimeType:'text/plain',buffer:fixture});await expect(page.getByTestId('card-hands')).toBeVisible({timeout:30000});await expect(page.getByRole('button',{name:'Cancel import'})).toHaveCount(0,{timeout:90000});const initial=await page.getByTestId('card-hands').innerText();
 await expect(page.getByTestId('card-splash')).toContainText('Estimated · 50:50');await page.getByRole('button',{name:'BB',exact:true}).click();await expect(page.getByTestId('card-net')).toContainText('bb');await page.getByRole('button',{name:'Non-Showdown',exact:true}).click();await expect(page.getByRole('button',{name:'Non-Showdown',exact:true})).toHaveAttribute('aria-pressed','false');await page.getByRole('button',{name:'Reset zoom'}).click();
 await page.getByLabel('Limit',{exact:true}).selectOption({index:0});await expect(page.getByTestId('card-hands')).not.toHaveText(initial);await page.getByRole('button',{name:'Clear filters'}).click();await page.getByLabel('Position',{exact:true}).selectOption({index:0});await expect(page.getByTestId('card-hands')).not.toHaveText(initial);await page.getByRole('button',{name:'Clear filters'}).click();
 await page.getByLabel('Period',{exact:true}).selectOption('Custom Range');await page.getByLabel('From date').fill('2026-01-01');await page.getByLabel('To date').fill('2026-12-31');await page.getByRole('button',{name:'Clear filters'}).click();
 for(const tab of ['Days','Months','Limits','Positions']){await page.getByRole('button',{name:tab,exact:true}).click();await expect(page.locator('tfoot')).toContainText('TOTAL');await expect(page.getByRole('button',{name:'Sort Rake bb/100',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Sort Splash Fee bb/100',exact:true})).toBeAttached();await page.getByRole('button',{name:'Sort Hands'}).click();if(tab==='Days'||tab==='Months'){await page.locator('tbody tr').first().click();await expect(page.getByLabel('Period',{exact:true})).toHaveValue(tab==='Days'?'Day':'Month');await page.getByRole('button',{name:'Clear filters'}).click();}}
 await page.getByRole('button',{name:'Days',exact:true}).click();await page.getByRole('columnheader').nth(1).dragTo(page.getByRole('columnheader').nth(3));await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('coinpoker.ui.v1')!).orders.Days)).not.toEqual(['key','hands','hours','vpip','pfr','threeBet','net','bb100','evBB100','rake','rakeBB100','fee','feeBB100','wtsd','wsd','wwsf']);
 await page.getByText('Data Quality / Coverage', {exact:false}).click();await expect(page.getByText('BOMBPOT_EV_UNSUPPORTED',{exact:true})).toHaveCount(0);await page.getByLabel('Game Type').selectOption('');await expect(page.getByText('BOMBPOT_EV_UNSUPPORTED',{exact:true})).toBeVisible();
 const settings=await page.evaluate(()=>localStorage.getItem('coinpoker.ui.v1'));await page.reload();await expect(page.getByRole('button',{name:'BB',exact:true})).toHaveAttribute('aria-pressed','true');expect(await page.evaluate(()=>localStorage.getItem('coinpoker.ui.v1'))).toBe(settings);
 await page.getByLabel('Select CoinPoker file').setInputFiles({name:'duplicate.txt',mimeType:'text/plain',buffer:Buffer.concat([fixture,Buffer.from('\n'),fixture])});await expect(page.getByTestId('card-hands')).toBeVisible();await expect(page.getByRole('button',{name:'Cancel import'})).toHaveCount(0);await page.getByText('Data Quality / Coverage',{exact:false}).click();await expect(page.getByText(/Duplicates: [1-9]/)).toBeVisible();
 await page.getByLabel('Select CoinPoker file').setInputFiles({name:'bad.txt',mimeType:'text/plain',buffer:Buffer.from('not hand history')});await expect(page.getByRole('alert')).toContainText('No CoinPoker hands');await expect(page.getByTestId('card-hands')).toBeVisible();
 await page.getByLabel('Select CoinPoker file').setInputFiles({name:'cancel.txt',mimeType:'text/plain',buffer:Buffer.concat(Array(1000).fill(fixture))});await page.getByLabel('Game Type').selectOption('BombPot');await expect(page.getByTestId('card-vpip')).toContainText('—');await page.getByRole('button',{name:'Cancel import'}).click();await expect(page.getByRole('alert')).toContainText('cancelled');await expect(page.getByTestId('card-hands')).toBeVisible();expect(errors).toEqual([]);await page.screenshot({path:'analysis/phase2b-fixture.png',fullPage:true});
});
test('full source browser regression and worker responsiveness',async({page,browser})=>{test.setTimeout(300000);const source=process.env.COINPOKER_SOURCE;test.skip(!source || !fs.existsSync(source),'Set COINPOKER_SOURCE to run the private full-dataset regression.');if(!source)return;const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.evaluate(()=>{(window as unknown as {beats:number}).beats=0;setInterval(()=>{(window as unknown as {beats:number}).beats++;},50);});const start=Date.now();await page.getByLabel('Select CoinPoker file').setInputFiles(source);await expect(page.getByTestId('card-hands')).toContainText('95,739',{timeout:150000});const firstMs=Date.now()-start;await page.getByRole('button',{name:'BB',exact:true}).click();await expect(page.getByRole('button',{name:'BB',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'₮',exact:true}).click();await expect(page.getByRole('button',{name:'Cancel import'})).toHaveCount(0,{timeout:180000});
 await expect(page.getByTestId('card-net')).toContainText('₮5,536.72');const nlh=await page.evaluate(()=>({net:window.latestResult.summary.net.toString(),financial:window.latestResult.summary.financialHands,bb100:window.latestResult.summary.bb100,evBB100:window.latestResult.summary.evBB100,hours:window.latestResult.summary.hours}));await page.getByLabel('Game Type').selectOption('');await expect(page.getByTestId('card-hands')).toContainText('95,750');
 for(const [card,text] of [['net','₮5,525.53'],['bb100','1.72'],['evBB100','0.88'],['hours','323.55'],['vpip','25.82%'],['pfr','20.90%'],['threeBet','12.28%'],['wtsd','31.50%'],['wsd','55.18%'],['wwsf','52.31%']])await expect(page.getByTestId('card-'+card)).toContainText(text!);
 const reconciliation=await page.evaluate(()=>{const r=window.latestResult;return {net:r.summary.net.toString(),sd:r.summary.sd.toString(),nsd:r.summary.nsd.toString(),financial:r.summary.financialHands,bb100:r.summary.bb100,evBB100:r.summary.evBB100,hours:r.summary.hours,last:r.points.at(-1),timing:r.database.timing,hash:r.database.hash,queryMs:r.latency};});expect(reconciliation.net).toBe('552553');expect(reconciliation.sd).toBe('2284325');expect(reconciliation.nsd).toBe('-1731772');expect(reconciliation.financial).toBe(95647);expect(reconciliation.bb100).toBeCloseTo(1.7215,4);expect(reconciliation.evBB100).toBeCloseTo(.8829,4);expect(reconciliation.hours).toBeCloseTo(323.5492,4);expect(reconciliation.last!.currency[0]).toBe(5525.53);expect(reconciliation.last!.currency[1]!+reconciliation.last!.currency[2]!).toBeCloseTo(5525.53,8);expect(100*reconciliation.last!.bb[3]!/95647).toBeCloseTo(reconciliation.evBB100!,10);fs.writeFileSync('analysis/phase2b-browser-reconciliation.json',JSON.stringify({nlh,all:reconciliation},null,2));
 await page.getByText('Data Quality / Coverage',{exact:false}).click();await expect(page.getByText('Parsed: 95,750 · Unique: 95,750')).toBeVisible();await page.getByLabel('Game Type').selectOption('');await expect(page.getByTestId('card-hands')).toContainText('95,750');await expect(page.getByText('Financial unavailable: 103')).toBeVisible();await expect(page.getByText('unsupported: 11',{exact:true})).toBeVisible();
 const workerEvidence=await page.evaluate(async()=>{return {beats:(window as unknown as {beats:number}).beats,memory:(performance as unknown as {memory?:{usedJSHeapSize:number}}).memory?.usedJSHeapSize};});const filterStart=Date.now();await page.getByLabel('Limit',{exact:true}).selectOption('200');await expect(page.getByTestId('card-hands')).not.toContainText('95,750');await page.getByRole('button',{name:'Days',exact:true}).click();await expect(page.locator('tfoot')).toContainText('TOTAL');await expect(page.getByRole('button',{name:'Sort Rake bb/100',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Sort Splash Fee bb/100',exact:true})).toBeAttached();await page.getByRole('button',{name:'Clear filters'}).click();await expect(page.getByTestId('card-hands')).toContainText('95,739');await page.screenshot({path:'analysis/phase2b-full.png',fullPage:true});fs.writeFileSync(path.resolve('analysis/phase2b-browser-benchmark.json'),JSON.stringify({browser:browser.version(),firstUsableMs:firstMs,totalMs:Date.now()-start,filterFlowMs:Date.now()-filterStart,...workerEvidence,errors},null,2));expect(errors).toEqual([]);
});
