import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {importHands,processHand,Deduplicator,canonicalContent} from '../src/import/core.ts';
import {scanLines,scanHands} from '../src/parser/scanner.ts';
import {money,rational,add,ratioNumber} from '../src/core/value.ts';
import {buildSessions,clipIntervals} from '../src/metrics/sessions.ts';
import {Aggregate,matches} from '../src/metrics/aggregate.ts';
import {calculateSplash} from '../src/special/splash.ts';
import {evaluate,cardId,cardName} from '../src/equity/evaluator.ts';
import {exactEquity} from '../src/equity/enumerator.ts';
import {referenceEvaluate,referenceEquity} from './reference.ts';
import type {ProcessedHand} from '../src/import/core.ts';
async function fixture(id:string,equity=false):Promise<ProcessedHand>{for await(const p of importHands(fs.createReadStream(`tests/fixtures/${id}.txt`),{equity}))return p;throw Error('Missing fixture');}
async function textHand(s:string,equity=false){async function* chunks(){yield new TextEncoder().encode(s);}for await(const p of importHands(chunks(),{equity}))return p;throw Error('Empty');}
for(const file of fs.readdirSync('tests/fixtures'))test('real grammar '+file,async()=>{const p=await fixture(file.replace('.txt',''));assert.equal(p.hand.diagnostics.filter(d=>d.severity==='error').length,0);assert.equal(p.hand.handId,file.replace('.txt',''));assert.equal(p.hand.tokens.length,p.hand.raw.lines.length);});
test('exact decimal money and grouping',()=>{assert.equal(money('₮1,085.72'),108572n);assert.equal(money('0.1'),10n);assert.throws(()=>money('1,08'));assert.throws(()=>money('0.001'));});
const financial:Record<string,[bigint,boolean]>={'900000010':[-116n,false],'900000004':[345n,false],'900000005':[-2062n,true],'900000006':[3550n,false],'900000001':[66n,false],'900000011':[-10000n,true],'900000019':[10276n,true],'900000020':[-11n,true]};
for(const [id,[net,sd]] of Object.entries(financial))test('financial independent sanity '+id,async()=>{const p=await fixture(id);assert.equal(p.hero.netWon.value,net);assert.equal(p.hero.logicalShowdown.value,sd);assert.equal(p.hero.showdownWon.value!+p.hero.nonShowdownWon.value!,net);});
test('unknown auto and global residual independent Hero validity',async()=>{assert.equal((await fixture('900000009')).hero.netWon.value,null);const p=await fixture('900000015');assert.equal(p.hero.netWon.value,-16n);assert.notEqual(p.ledger.payoutResidual,0n);assert.equal((await fixture('900000012')).hero.netWon.status,'available');});
test('VPIP forced excluded, returned raise retained',async()=>{const fold=await fixture('900000010'),win=await fixture('900000004');assert.equal(fold.hero.vpip.value,false);assert.equal(fold.hero.pfr.value,false);assert.equal(win.hero.vpip.value,true);assert.equal(win.hero.pfr.value,true);});
test('negative split still showdown win; metrics denominators',async()=>{const p=await fixture('900000020'),a=new Aggregate();a.push(p);assert.equal(a.stats.wsd.numerator,1);assert.equal(a.stats.wsd.denominator,1);assert.equal(a.stats.wwsf.numerator,1);});
test('HU and unsorted seats positions',async()=>{assert.equal((await fixture('900000001')).hero.position.value,'BB');assert.equal((await fixture('900000004')).hero.position.value,'SB');assert.equal((await fixture('900000006')).hero.position.value,'BB');});
test('threebet opportunity and made on real Hero reraise',async()=>{const p=await fixture('900000005');assert.equal(p.hero.threeBetOpportunity.value,true);assert.equal(p.hero.threeBetMade.value,true);});
test('side layers preserve dead money',async()=>{const p=await fixture('900000003');assert.deepEqual(p.pots.value?.map(p=>p.gross),[34029n,9602n]);assert.deepEqual((await fixture('900000023')).pots.value?.map(p=>p.gross),[47637n,4034n]);});
test('dedup retains immutable conflict and repeated awards',async()=>{const p=await fixture('900000023'),d=new Deduplicator(),s=canonicalContent(p.hand.raw);assert.equal(d.accept(p.hand.handId,s,p.hand.raw),'insert');assert.equal(d.accept(p.hand.handId,s,p.hand.raw),'duplicate');assert.equal(d.accept(p.hand.handId,s+' changed',p.hand.raw),'conflict');assert.equal(d.accepted.size,1);assert.equal(d.conflicts.length,1);assert.equal(p.ledger.players.find(p=>p.name==='Player109')?.collected,51171n);});
test('stream BOM CRLF arbitrary single-byte UTF8 chunks and EOF',async()=>{const s='\uFEFF'+fs.readFileSync('tests/fixtures/900000004.txt','utf8').replace(/\r?\n/g,'\r\n').trimEnd();async function* chunks(){for(const b of new TextEncoder().encode(s))yield Uint8Array.of(b);}const hands=[];for await(const h of scanHands(scanLines(chunks())))hands.push(h);assert.equal(hands.length,1);assert.equal(processHand(hands[0]!,{equity:false}).hero.netWon.value,345n);});
test('unknown monetary and truncated hands preserved; next hand survives',async()=>{const s=fs.readFileSync('tests/fixtures/900000004.txt','utf8');const p=await textHand(s.replace('*** SUMMARY ***','Hero: unknown payment ₮5\n*** SUMMARY ***'));assert(p.hand.diagnostics.some(d=>d.code==='UNKNOWN_MONETARY_LINE'));assert.equal(p.hero.netWon.value,null);const q=await textHand(s.slice(0,s.indexOf('*** SUMMARY ***')));assert.equal(q.hero.netWon.value,null);});
test('cancel does not yield partial hand',async()=>{const controller=new AbortController();controller.abort();async function* chunks(){yield new Uint8Array([10]);}await assert.rejects(async()=>{for await(const _ of importHands(chunks(),{signal:controller.signal})){};});});
test('sessions overlap, exact gap, >30min and clipping',()=>{const base={timezoneRaw:'MSK'};const intervals=[{...base,handId:'1',start:0,end:600},{...base,handId:'2',start:300,end:1200},{...base,handId:'3',start:1500,end:1800},{...base,handId:'4',start:3600,end:3700},{...base,handId:'5',start:5501,end:5600}];const s=buildSessions(intervals);assert.equal(s.length,2);assert.equal(s[0]!.estimatedSpanSeconds,3700);assert.equal(s[0]!.observedUnionSeconds,1600);assert.equal(clipIntervals(intervals,500,1000).length,2);});
test('Splash defaults to estimated 50:50 and shares only among dealt-in players',async()=>{
 const p=await fixture('900000016');assert.equal(p.splash.splashRatio.value?.status,'estimated');assert.deepEqual(p.splash.sharedSplashPool.value,rational(600n));assert.deepEqual(p.splash.winnerSplashPool.value,rational(600n));assert.deepEqual(p.splash.heroSplashReceived.value,rational(120n));assert.equal(p.hero.netWon.value,-8348n);
 p.hand.players.push({name:'SittingOut',seat:6,startingStack:20000n,dealtIn:false,cards:null});assert.deepEqual(calculateSplash(p.hand).heroSharedSplashReceived.value,rational(120n));
 p.hand.players.find(p=>p.name==='Hero')!.dealtIn=false;assert.deepEqual(calculateSplash(p.hand).heroSharedSplashReceived.value,rational(0n));
 for(const player of p.hand.players)player.dealtIn=false;assert.equal(calculateSplash(p.hand).heroSplashReceived.value,null);
});
test('Splash preserves explicit ratios and attributes pot share to winner',async()=>{
 const p=await fixture('900000016');p.hand.actions=p.hand.actions.map(a=>a.kind==='collected'?{...a,player:'Hero'}:a);
 assert.deepEqual(calculateSplash(p.hand).heroSplashReceived.value,rational(720n));
 const s=calculateSplash(p.hand,[{tableId:p.hand.tableId,fromDate:'2026-01-01',toDate:'2026-12-31',sharedRatio:rational(1n,4n),winnerRatio:rational(3n,4n),source:'test confirmation',status:'confirmed'}]);assert.equal(s.splashCalculationStatus,'available');assert.deepEqual(s.heroSplashReceived.value,rational(960n));assert.equal(s.splashRatio.value?.status,'confirmed');
});
test('BombPot distinct from RIT, cashout facts preserved',async()=>{const b=await fixture('900000013');assert.equal(b.hand.gameType,'BombPot');assert.equal(b.hand.runMode,'with two boards');assert.equal(b.hero.vpip.status,'unsupported');assert.equal((await fixture('900000019')).hand.actions.filter(a=>a.kind==='cashout').length,1);});
test('RIT2/3 are one hand and preserve full boards',async()=>{for(const [id,runs] of [['900000018',2],['900000014',3]] as const){const p=await fixture(id);assert.equal(p.hand.runCount,runs);assert.equal(Object.keys(p.hand.boards).length,runs);assert(Object.values(p.hand.boards).every(b=>b.length===5));}});
test('mixed stakes normalized per hand',async()=>{const p=await fixture('900000004'),q=await fixture('900000004');p.hero.netWon.value=1000n;p.hero.nonShowdownWon.value=1000n;q.hero.netWon.value=-1000n;q.hero.nonShowdownWon.value=-1000n;q.hand.bigBlind=200n;const a=new Aggregate();a.push(p);a.push(q);assert.equal(a.result().bb100,250);assert(matches(p,{limit:'NL100',month:'2026-03'}));});
test('production evaluator independent random seven-card reference',()=>{let seed=91;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed;};for(let i=0;i<500;i++){const deck=Array.from({length:52},(_,j)=>j);for(let j=0;j<7;j++){const k=j+random()%(52-j);[deck[j],deck[k]]=[deck[k]!,deck[j]!];}const c=deck.slice(0,7);assert.equal(evaluate(c),referenceEvaluate(c));}});
for(const [name,holes,board] of [
 ['flop',[['Ah','Ad'],['Ks','Kh']],['2c','3d','4s']],['turn',[['Ah','Ad'],['Ks','Kh']],['2c','3d','4s','5c']],['river',[['Ah','Ad'],['Ks','Kh']],['2c','3d','4s','5c','7h']],['tie',[['Ah','Ad'],['Ks','Kh']],['Tc','Jc','Qc','Kc','Ac']],['threeway',[['Ah','Ad'],['Ks','Kh'],['Qs','Qh']],['2c','3d','4s']]
] as [string,string[][],string[]][])test('exact vs independent reference '+name,()=>{assert.deepEqual(exactEquity(holes,board),referenceEquity(holes,board));});
test('preflop exact vs independent exhaustive reference',()=>{const holes=[['Ah','Ks'],['Qs','Qd']];const p=exactEquity(holes,[]),r=referenceEquity(holes,[]);assert.deepEqual(p,r);assert.equal(p.scenarioCount,1712304);});
test('equity symmetry, suit and player permutation; sum and ties',()=>{const h=[['Ah','Ad'],['Ks','Kh']],b=['2c','3d','4s'];const p=exactEquity(h,b),q=exactEquity([...h].reverse(),b);assert.deepEqual(p.shares,[...q.shares].reverse());const rotate=(c:string)=>cardName((cardId(c)&~3)|((cardId(c)+1)&3));assert.deepEqual(p,exactEquity(h.map(a=>a.map(rotate)),b.map(rotate)));assert.deepEqual(p.shares.reduce(add,rational(0n)),rational(1n));assert.deepEqual(exactEquity(h,['Tc','Jc','Qc','Kc','Ac']).shares,[rational(1n,2n),rational(1n,2n)]);assert.throws(()=>exactEquity([['Ah'],['Kh','Ks']],[]));});
test('all-in snapshot preflop never removes future board; tracker adjusted payout',async()=>{const p=await fixture('900000011',true);assert.equal(p.allInEV?.evCoverage,'fullyAdjusted');assert.equal(p.allInEV.pots[0]?.snapshot?.board.length,0);assert.equal(p.allInEV.pots[0]?.equities?.scenarioCount,1712304);assert.equal(p.allInEV.adjustedResult.value!.n*1n===0n,false);const e=ratioNumber(p.allInEV.pots[0]!.equities!.shares[p.pots.value![0]!.eligible.indexOf('Hero')]!);assert(Math.abs(ratioNumber(p.allInEV.adjustedResult.value!)-(19914*e-10000))<1e-8);});



