import {useEffect,useRef} from 'react';
import * as echarts from 'echarts/core';
import {LineChart} from 'echarts/charts';
import {GridComponent,TooltipComponent,DataZoomComponent} from 'echarts/components';
import {CanvasRenderer} from 'echarts/renderers';
import type {Point} from './data.ts';
echarts.use([LineChart,GridComponent,TooltipComponent,DataZoomComponent,CanvasRenderer]);
export const names=['Net Won','Non-Showdown','Showdown','All-in EV'];
const colors=['#40d7a0','#f57280','#6aafff','#ffb15b'];
export function ChartPanel({points,unit,lines,setLines,evReady}:{points:Point[];unit:string;lines:boolean[];setLines:(v:boolean[])=>void;evReady:boolean}) {const element=useRef<HTMLDivElement>(null),instance=useRef<echarts.ECharts|null>(null);useEffect(()=>{const c=echarts.init(element.current!,undefined,{renderer:'canvas'});instance.current=c;const resize=new ResizeObserver(()=>c.resize());resize.observe(element.current!);return ()=>{resize.disconnect();c.dispose();};},[]);
 useEffect(()=>{const c=instance.current!;c.setOption({animation:false,backgroundColor:'transparent',textStyle:{color:'#91a2b5',fontFamily:'Inter, Segoe UI, sans-serif'},grid:{left:78,right:32,top:30,bottom:80},tooltip:{trigger:'axis',backgroundColor:'#182331',borderColor:'#33465b',textStyle:{color:'#e6eef7'},formatter:(params:unknown)=>{const arr=params as {value:[number,number]}[];const idx=(arr[0]?.value[0]??1)-1,p=points[idx];if(!p)return '';const values=unit==='BB'?p.bb:p.currency;return `Hand #${idx+1} · ${echarts.format.encodeHTML(p.id)}<br/>${echarts.format.encodeHTML(p.date)}<br/>${echarts.format.encodeHTML(p.limit)} · ${echarts.format.encodeHTML(p.position)}<br/>`+names.map((n,i)=>`${n}: ${values[i]!.toFixed(2)} ${unit==='BB'?'bb':'₮'}`).join('<br/>');}},xAxis:{type:'value',min:1,max:Math.max(points.length,2),name:'Hands',axisLine:{lineStyle:{color:'#334052'}},splitLine:{show:false}},yAxis:{type:'value',name:unit==='BB'?'bb':'₮',splitLine:{lineStyle:{color:'#253244'}}},dataZoom:[{type:'inside',filterMode:'none',zoomOnMouseWheel:true,moveOnMouseMove:true},{type:'slider',filterMode:'none',height:24,bottom:20,borderColor:'#334052',fillerColor:'#35567755',textStyle:{color:'#91a2b5'}}],series:names.map((name,i)=>({name,type:'line',showSymbol:false,sampling:'lttb',lineStyle:{width:1.7,color:colors[i]},itemStyle:{color:colors[i]},data:lines[i]&&(i!==3||evReady)?points.map((p,j)=>[j+1,(unit==='BB'?p.bb:p.currency)[i]]):[]}))},true);},[points,unit,lines,evReady]);return <section className="panel chart-panel"><div className="section-head"><div><h2>Results</h2><small>Chronological hands · financial-valid universe</small></div><button onClick={()=>instance.current?.dispatchAction({type:'dataZoom',start:0,end:100})}>Reset zoom</button></div><div className="legend">{names.map((n,i)=><button key={n} aria-label={n} aria-pressed={lines[i]} style={{borderColor:lines[i]?colors[i]:undefined}} onClick={()=>setLines(lines.map((v,j)=>j===i?!v:v))}><span style={{color:colors[i]}}>●</span> {n}{i===3&&!evReady?' · calculating…':''}</button>)}</div><div ref={element} className="chart" aria-label="Cumulative results chart"/><div className="chart-note">Wheel to zoom · drag to pan · {points.length.toLocaleString()} financial hands</div></section>;}
