import {Aggregate} from '../metrics/aggregate.ts';
import {buildSessions,clipIntervals,type Interval,type Session} from '../metrics/sessions.ts';
import {add,rational,mul,ratioNumber,type Rational} from '../core/value.ts';
import type {ProcessedHand} from '../import/core.ts';
import type {HeroMetrics} from '../metrics/hero.ts';
import type {AllInEV} from '../equity/allInEV.ts';
import type {Hand} from '../parser/model.ts';
export type Tab='Days'|'Months'|'Limits'|'Positions';
export interface Filters {period:string;from:string;to:string;month:string;limits:string[];positions:string[];tables:string[];players:string;game:string;splash:string}
export const defaults:Filters={period:'All Time',from:'',to:'',month:'',limits:[],positions:[],tables:[],players:'',game:'NLH',splash:''};
export interface Fact {hand:Pick<Hand,'handId'|'startedAt'|'endedAt'|'bigBlind'|'tableId'|'gameType'|'splashType'|'handSplashFee'>;players:number;hero:HeroMetrics;ev:AllInEV|null;splash:Rational|null;splashShared:Rational|null;reasons:string[];interval:Interval|null}
export function fact(p:ProcessedHand):Fact {const h=p.hand;return {hand:{handId:h.handId,startedAt:h.startedAt,endedAt:h.endedAt,bigBlind:h.bigBlind,tableId:h.tableId,gameType:h.gameType,splashType:h.splashType,handSplashFee:h.handSplashFee},players:h.players.length,hero:p.hero,ev:p.allInEV,splash:p.splash.heroSplashReceived.value,splashShared:p.splash.heroSharedSplashReceived.value,reasons:[...new Set([...h.diagnostics.map(d=>d.code),...Object.values(p.hero).flatMap(v=>v.reasonCodes),...(h.splashType!=='none'?p.splash.heroSplashReceived.reasonCodes:[])])],interval:h.startedAt&&h.endedAt?{handId:h.handId,start:h.startedAt.ordinalSeconds,end:h.endedAt.ordinalSeconds,timezoneRaw:h.startedAt.timezoneRaw}:null};}
export function accepts(f:Fact,q:Filters):boolean {const h=f.hand,d=h.startedAt?.dateKey??'',m=h.startedAt?.monthKey??'';return (!q.from||d>=q.from)&&(!q.to||d<=q.to)&&(!q.month||m===q.month)&&(!q.limits.length||q.limits.includes(h.bigBlind.toString()))&&(!q.positions.length||q.positions.includes(f.hero.position.value??'Unavailable'))&&(!q.tables.length||q.tables.includes(h.tableId))&&(!q.players||f.players===Number(q.players))&&(!q.game||h.gameType===q.game)&&(!q.splash||q.splash==='any'&&h.splashType!=='none'||q.splash===h.splashType);}
function union(intervals:Interval[]):number {return buildSessions(intervals).reduce((n,s)=>n+s.observedUnionSeconds,0);}
export function hours(facts:Fact[],sessions:Session[],q:Filters):{hours:number;observed:number} {const intervals=facts.flatMap(f=>f.interval?[f.interval]:[]),from=q.from?Date.parse(q.from+'T00:00:00Z')/1000:-Infinity,to=q.to?Date.parse(q.to+'T00:00:00Z')/1000+86400:Infinity;const monthFrom=q.month?Date.parse(q.month+'-01T00:00:00Z')/1000:from;const monthTo=q.month?Date.UTC(Number(q.month.slice(0,4)),Number(q.month.slice(5,7)),1)/1000:to;const lo=Math.max(from,monthFrom),hi=Math.min(to,monthTo);const dimension=q.limits.length||q.positions.length||q.tables.length||q.players||q.splash||q.game&&q.game!=='NLH';return {hours:(dimension?union(clipIntervals(intervals,lo,hi)):sessions.reduce((n,s)=>n+Math.max(0,Math.min(s.end,hi)-Math.max(s.start,lo)),0))/3600,observed:union(clipIntervals(intervals,lo,hi))/3600};}
export function summarize(facts:Fact[],sessions:Session[],q:Filters) {const a=new Aggregate();let corrections=rational(0n),rake=0n,rakeCount=0,fee=0n,feeCount=0,rakeBB=rational(0n),feeBB=rational(0n),rakeBBCount=0,feeBBCount=0,splash=rational(0n),splashUnknown=0,splashEvents=0,splashIncluded=0;const coverage:Record<string,number>={},reasons:Record<string,number>={};for(const f of facts){
 // Narrow adapter: Aggregate consumes only hand.bigBlind, hero and allInEV; raw/parser/ledger objects stay out of the query store.
 a.push({hand:f.hand,hero:f.hero,allInEV:null} as ProcessedHand);
 // Sum the core's exact corrections separately. Adding unchanged actual cents to
 // a large equity denominator on every non-all-in hand is needlessly expensive.
 if(f.hero.netWon.value!==null&&f.hand.bigBlind>0n&&f.ev?.availableAdjustment.n)corrections=add(corrections,mul(f.ev.availableAdjustment,rational(1n,f.hand.bigBlind)));
 if(f.hero.heroAttributedRake.value!==null){rake+=f.hero.heroAttributedRake.value;rakeCount++;if(f.hand.bigBlind>0n){rakeBB=add(rakeBB,rational(f.hero.heroAttributedRake.value,f.hand.bigBlind));rakeBBCount++;}}if(f.hero.heroAttributedSplashFee.value!==null){fee+=f.hero.heroAttributedSplashFee.value;feeCount++;if(f.hand.bigBlind>0n){feeBB=add(feeBB,rational(f.hero.heroAttributedSplashFee.value,f.hand.bigBlind));feeBBCount++;}}if(f.hand.splashType!=='none'){splashEvents++;const received=f.splash??f.splashShared;if(received!==null){splash=add(splash,received);splashIncluded++;}if(f.splash===null)splashUnknown++;}const ev=f.ev?.evCoverage??'pending';coverage[ev]=(coverage[ev]??0)+1;for(const r of new Set([...f.reasons,...(f.ev?.pots.flatMap(p=>p.reasonCodes)??[])]))reasons[r]=(reasons[r]??0)+1;
 }a.evBB=add(a.evBB,corrections);return {...a.result(),...hours(facts,sessions,q),bb:ratioNumber(a.bb),rake:Number(rake)/100,rakeCount,fee:Number(fee)/100,feeCount,rakeBB100:rakeBBCount?ratioNumber(mul(rakeBB,rational(100n,BigInt(rakeBBCount)))):null,feeBB100:feeBBCount?ratioNumber(mul(feeBB,rational(100n,BigInt(feeBBCount)))):null,rakeBBCount,feeBBCount,splash:splashEvents&&!splashIncluded?null:ratioNumber(splash)/100,splashEvents,splashUnknown,splashIncluded,coverage,reasons};}
export type Summary=ReturnType<typeof summarize>;
export interface Point {id:string;date:string;limit:string;position:string;currency:number[];bb:number[]}
export function chart(facts:Fact[]):Point[]{let net=0n,sd=0n,nsd=0n,correction=rational(0n);let nb=rational(0n),sb=rational(0n),nsb=rational(0n),correctionBB=rational(0n);return facts.flatMap(f=>{const h=f.hand,m=f.hero;if(m.netWon.value===null||h.bigBlind<=0n)return [];net+=m.netWon.value;sd+=m.showdownWon.value!;nsd+=m.nonShowdownWon.value!;const delta=f.ev?.availableAdjustment;if(delta?.n){correction=add(correction,delta);correctionBB=add(correctionBB,mul(delta,rational(1n,h.bigBlind)));}nb=add(nb,rational(m.netWon.value,h.bigBlind));sb=add(sb,rational(m.showdownWon.value!,h.bigBlind));nsb=add(nsb,rational(m.nonShowdownWon.value!,h.bigBlind));return [{id:h.handId,date:h.startedAt?.raw??'Unknown',limit:'NL'+Number(h.bigBlind),position:m.position.value??'Unavailable',currency:[Number(net)/100,Number(nsd)/100,Number(sd)/100,(Number(net)+ratioNumber(correction))/100],bb:[ratioNumber(nb),ratioNumber(nsb),ratioNumber(sb),ratioNumber(nb)+ratioNumber(correctionBB)]}];});}
export interface Database {filename:string;importedAt:string;parsed:number;unique:number;duplicates:number;conflicts:number;errors:number;hash:string;start:string;end:string;sessions:number;limits:string[];tables:string[];positions:string[];players:string[];timing:Record<string,number>}
export interface Result {summary:Summary;points:Point[];rows:Record<Tab,{key:string;summary:Summary}[]>;latency:number;evReady:boolean;database:Database}
export function query(facts:Fact[],sessions:Session[],q:Filters,database:Database,evReady:boolean):Result {const t=performance.now(),filtered=facts.filter(f=>accepts(f,q));const rows={} as Result['rows'];for(const tab of ['Days','Months','Limits','Positions'] as const){const groups=new Map<string,Fact[]>();for(const f of filtered){const k=tab==='Days'?f.hand.startedAt?.dateKey:tab==='Months'?f.hand.startedAt?.monthKey:tab==='Limits'?f.hand.bigBlind.toString():f.hero.position.value;const key=k??'Unavailable';const g=groups.get(key)??[];g.push(f);groups.set(key,g);}rows[tab]=[...groups].map(([key,fs])=>({key,summary:summarize(fs,sessions,{...q,...(tab==='Days'?{from:key,to:key,month:''}:tab==='Months'?{month:key}:tab==='Limits'?{limits:[key]}:{positions:[key]})})}));rows[tab].sort((a,b)=>tab==='Limits'?Number(a.key)-Number(b.key):tab==='Positions'?['UTG','HJ','CO','BTN','SB','BB','BTN_SB','Unavailable'].indexOf(a.key)-['UTG','HJ','CO','BTN','SB','BB','BTN_SB','Unavailable'].indexOf(b.key):b.key.localeCompare(a.key));}return {summary:summarize(filtered,sessions,q),points:chart(filtered),rows,latency:performance.now()-t,evReady,database};}
