import {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {defaults,type Filters,type Result,type Tab} from './data.ts';
import {ChartPanel} from './ChartPanel.tsx';
import {DataTable,columns,format,value} from './DataTable.tsx';
import './style.css';
interface Preferences {unit:string;lines:boolean[];filters:Filters;tab:Tab|'Overview';orders:Record<Tab,string[]>}
const initial:Preferences={unit:'₮',lines:[true,true,true,true],filters:defaults,tab:'Overview',orders:{Days:columns,Months:columns,Limits:columns,Positions:columns}};
function load():Preferences {try {const p=JSON.parse(localStorage.getItem('coinpoker.ui.v1')??'null') as Preferences|null;return p&&Array.isArray(p.lines)&&p.lines.length===4&&p.filters&&p.orders?{...initial,...p,orders:Object.fromEntries(Object.entries(p.orders).map(([k,v])=>[k,Array.isArray(v)&&v.length===columns.length&&new Set(v).size===columns.length&&v.every(c=>columns.includes(c))?v:columns])) as Preferences['orders']}:initial;}catch{return initial;}}
function App(){const [prefs,setPrefs]=useState(load),[result,setResult]=useState<Result|null>(null),[progress,setProgress]=useState<{stage:string;parsed:number;percent:number}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const active=useRef<Worker|null>(null),staging=useRef<Worker|null>(null),input=useRef<HTMLInputElement>(null),request=useRef(0),expected=useRef(new WeakMap<Worker,number>()),current=useRef(prefs);current.current=prefs;
 useEffect(()=>{try{localStorage.setItem('coinpoker.ui.v1',JSON.stringify(prefs));}catch{/* Private browsing/storage quota: settings remain in memory. */}},[prefs]);
 const ask=(w:Worker|null)=>{if(w){const id=++request.current;expected.current.set(w,id);w.postMessage({type:'query',filters:current.current.filters,request:id});}};
 useEffect(()=>{if(active.current){setBusy(true);ask(active.current);}if(staging.current)ask(staging.current);},[prefs.filters]);
 useEffect(()=>()=>{active.current?.terminate();staging.current?.terminate();},[]);
 function importFile(file:File){staging.current?.terminate();setError('');setProgress({stage:'Reading file',parsed:0,percent:0});const w=new Worker(new URL('./worker.ts',import.meta.url),{type:'module'});staging.current=w;w.onmessage=(e:MessageEvent<{type:string;payload:unknown}>)=>{if(w!==staging.current&&w!==active.current)return;const {type,payload}=e.data;if(type==='progress')setProgress(payload as typeof progress);if(type==='result'){const p=payload as {request:number;filters:Filters;result:Result};if(p.request!==expected.current.get(w))return;if(w===active.current||!active.current){setResult(p.result);setBusy(false);if(JSON.stringify(current.current.filters)!==JSON.stringify(p.filters))setPrefs(old=>({...old,filters:p.filters}));}}if(type==='complete'){active.current?.terminate();active.current=w;staging.current=null;setProgress(null);ask(w);}if(type==='error'){setError(String(payload));setProgress(null);if(w===staging.current){w.terminate();staging.current=null;}}};w.onerror=()=>{setError('The processing Worker stopped. Try importing again or use a smaller file.');setProgress(null);w.terminate();if(staging.current===w)staging.current=null;};ask(w);w.postMessage({type:'import',file});}
 const update=(patch:Partial<Preferences>)=>setPrefs(p=>({...p,...patch}));const filter=(patch:Partial<Filters>)=>setPrefs(p=>({...p,filters:{...p.filters,...patch}}));const q=prefs.filters,s=result?.summary;const multi=(label:string,key:'limits'|'positions'|'tables',options:string[])=> <label>{label}<select aria-label={label} multiple value={q[key]} onChange={e=>filter({[key]:Array.from(e.target.selectedOptions,o=>o.value)})}>{options.map(o=><option key={o} value={o}>{key==='limits'?'NL'+o:o.replace('BTN_SB','BTN/SB')}</option>)}</select></label>;
 const period=(p:string)=>{const now=new Date(),today=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');filter({period:p,from:p==='Today'?today:'',to:p==='Today'?today:'',month:p==='This Month'?today.slice(0,7):''});};
 const stats=[['Net Won','net','Poker Net Won; wallet Splash rewards excluded.'],['bb/100','bb100','100 × sum of each financial hand result / its own BB / eligible hands.'],['EV bb/100','evBB100','Primary All-in EV with actual fallback when exact adjustment is unavailable.'],['Hands','hands','Filtered hands; imported file count is shown in the header.'],['Hours Played','hours','Estimated session spans; gap greater than 30 min starts a session. Dimension filters use union of matching intervals.'],['VPIP','vpip','Voluntary preflop contributions / eligible hands.'],['PFR','pfr','Preflop raises / eligible hands.'],['3Bet','threeBet','3Bet actions / 3Bet opportunities.'],['WTSD','wtsd','Showdowns / hands where Hero saw the flop.'],['W$SD','wsd','Pot awards / showdowns.'],['WWSF','wwsf','Pot awards / hands where Hero saw the flop.'],['Rake','rake','Derived Hero attribution only where available.'],['Splash Fee','fee','Hand-level fees; absent summary fee stays unavailable.'],['Splash Received','splash','Historical table-specific distribution ratios are unknown; no estimate is made.']];
 return <main onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f)importFile(f);}}><header><div><div className="eyebrow">LOCAL POKER ANALYTICS</div><h1>CoinPoker <span>Dashboard</span></h1></div><div className="header-actions"><div className="unit" aria-label="Display unit">{['₮','BB'].map(u=><button key={u} aria-pressed={prefs.unit===u} onClick={()=>update({unit:u})}>{u}</button>)}</div><button className="primary" onClick={()=>input.current?.click()}>Load / Update Database</button><input ref={input} type="file" accept=".txt,text/plain" aria-label="Select CoinPoker file" hidden onChange={e=>{const f=e.target.files?.[0];if(f)importFile(f);e.target.value='';}}/></div></header>
 {error&&<div role="alert" className="error">{error}</div>}{progress&&<section className="panel import-progress" role="status"><div><strong>{progress.stage}…</strong><span>{progress.parsed.toLocaleString()} hands · {progress.percent.toFixed(0)}%</span></div><progress value={progress.percent} max={100}/><button onClick={()=>{staging.current?.terminate();staging.current=null;setProgress(null);setError('Import cancelled. Previous completed database retained.');if(!active.current)setResult(null);}}>Cancel import</button></section>}
 {!result&&!progress&&<section className="panel import-empty"><div className="import-icon">↥</div><h2>Drop your CoinPoker hand history file here</h2><p>Explore your results, all-in EV and poker statistics.</p><button className="primary" onClick={()=>input.current?.click()}>Choose .txt file</button><p className="muted">Your file stays on this device.</p></section>}
 {result&&s&&<><section className="database"><span className="status-dot"/><strong>{result.database.filename}</strong><span>{result.database.unique.toLocaleString()} imported hands</span><span>{result.database.start} → {result.database.end}</span><span>Imported {new Date(result.database.importedAt).toLocaleString()}</span></section><section className="panel filters"><div className="section-head"><h2>Global filters</h2><button onClick={()=>filter(defaults)}>Clear filters</button></div><div className="filter-grid"><label>Period<select aria-label="Period" value={q.period} onChange={e=>period(e.target.value)}>{['All Time','Today','Day','This Month','Month','Custom Range'].map(p=><option key={p}>{p}</option>)}</select></label>{['Day','Custom Range'].includes(q.period)&&<><label>From<input aria-label="From date" type="date" value={q.from} onChange={e=>filter({from:e.target.value,...(q.period==='Day'?{to:e.target.value}:{})})}/></label>{q.period==='Custom Range'&&<label>To<input aria-label="To date" type="date" value={q.to} onChange={e=>filter({to:e.target.value})}/></label>}</>}{q.period==='Month'&&<label>Month<input aria-label="Month" type="month" value={q.month} onChange={e=>filter({month:e.target.value})}/></label>}{multi('Limit','limits',result.database.limits)}{multi('Position','positions',result.database.positions)}<label>Players<select aria-label="Players" value={q.players} onChange={e=>filter({players:e.target.value})}><option value="">All</option>{result.database.players.map(p=><option key={p} value={p}>{p}-handed</option>)}</select></label><label>Game Type<select aria-label="Game Type" value={q.game} onChange={e=>filter({game:e.target.value})}><option value="">All</option><option>NLH</option><option value="BombPot">BombPot</option></select></label><label>Splash<select aria-label="Splash" value={q.splash} onChange={e=>filter({splash:e.target.value})}><option value="">All</option><option value="none">Regular Hands</option><option value="regular">Splash</option><option value="mega">Mega Splash</option><option value="any">Any Splash</option></select></label><details><summary>Tables</summary>{multi('Table','tables',result.database.tables)}</details></div><div className="chips">{[q.game,...q.limits.map(x=>'NL'+x),...q.positions,...q.tables,q.players&&q.players+' players',q.splash,q.from,q.to,q.month].filter(Boolean).map((x,i)=><span key={i}>{x}</span>)}<small>{busy?'Updating…':`${s.hands.toLocaleString()} filtered hands · ${result.latency.toFixed(0)} ms query`}</small></div></section>
 <section className="cards">{stats.map(([label,c,tip])=>{let n=c==='splash'?s.splash:value(s,c!,prefs.unit);const pending=c==='evBB100'&&!result.evReady;const metric=s.stats[c!];const coverage=c==='rake'?`${s.rakeCount}/${s.hands} attributed`:c==='fee'?`${s.feeCount}/${s.hands} known`:c==='net'?`${s.financialHands}/${s.hands} financial`:metric?`${metric.numerator}/${metric.denominator}; ${metric.excluded} unavailable`:'';return <article className="stat" key={label} data-testid={'card-'+c} title={tip+' '+coverage}><div>{label} <span tabIndex={0} aria-label={tip}>ⓘ</span></div><strong className={c==='net'?(n!==null&&n<0?'negative':'positive'):''}>{pending?'Calculating…':c==='splash'?n===null?'—':'₮'+n.toFixed(2):format(n,c!,prefs.unit)}</strong><small>{c==='splash'&&n===null?'Ratio unavailable':coverage|| (c==='hours'?'Estimated session span':c==='evBB100'?'Actual fallback included':'')}</small></article>;})}</section><ChartPanel points={result.points} unit={prefs.unit} lines={prefs.lines} setLines={lines=>update({lines})} evReady={result.evReady}/>
 <nav className="tabs" aria-label="Analysis tables">{['Overview','Days','Months','Limits','Positions'].map(t=><button key={t} aria-pressed={prefs.tab===t} onClick={()=>update({tab:t as Preferences['tab']})}>{t}</button>)}</nav><DataTable key={prefs.tab} tab={prefs.tab==='Overview'?'Limits':prefs.tab} result={result} unit={prefs.unit} order={prefs.orders[prefs.tab==='Overview'?'Limits':prefs.tab]} setOrder={o=>update({orders:{...prefs.orders,[prefs.tab==='Overview'?'Limits':prefs.tab]:o}})} onRow={key=>{const tab=prefs.tab==='Overview'?'Limits':prefs.tab;if(key==='Unavailable')return;if(tab==='Days')filter({period:'Day',from:key,to:key,month:''});else if(tab==='Months')filter({period:'Month',from:'',to:'',month:key});else if(tab==='Limits')filter({limits:[key]});else filter({positions:[key]});}}/>
 <details className="panel diagnostics"><summary>Data Quality / Coverage <span>{s.financialHands.toLocaleString()} / {s.hands.toLocaleString()} financial-valid · {s.hands? (100*s.financialHands/s.hands).toFixed(2):'—'}%</span></summary><div className="coverage-grid"><div><h3>Import</h3><p>Parsed: {result.database.parsed.toLocaleString()} · Unique: {result.database.unique.toLocaleString()}</p><p>Duplicates: {result.database.duplicates} · Conflicts: {result.database.conflicts}</p><p>Parsing errors: {result.database.errors} · Sessions: {result.database.sessions}</p></div><div><h3>Filtered coverage</h3><p>Financial unavailable: {s.excludedFinancial}</p><p>3Bet facts: {(100*(s.stats.threeBet?.coverage??0)).toFixed(2)}%</p><p>Rake attribution: {s.rakeCount}/{s.hands}</p><p>Splash ratios: {s.splashEvents-s.splashUnknown}/{s.splashEvents}</p><p>Observed interval union: {s.observed.toFixed(4)} h</p></div><div><h3>All-in EV</h3>{Object.entries(s.coverage).map(([k,v])=><p key={k}>{k}: {v}</p>)}<p>Candidates: {Object.entries(s.coverage).filter(([k])=>!['notApplicable','pending'].includes(k)).reduce((n,[,v])=>n+v,0)}</p></div></div><table><thead><tr><th>Reason</th><th>Hands</th></tr></thead><tbody>{Object.entries(s.reasons).map(([r,n])=><tr key={r}><td className="text">{r.toLowerCase().replaceAll('_',' ')}<small>{r}</small></td><td>{n}</td></tr>)}</tbody></table><p className="provenance">Schema 2 · Parser 0.2.0 · Metrics Phase 2A · EV tracker-snapshot-v1 · Evaluator exact-v1<br/>Source SHA-256: {result.database.hash}<br/>Parse: {(result.database.timing.parseMs!/1000).toFixed(2)} s · EV: {((result.database.timing.evMs??0)/1000).toFixed(2)} s · Total: {((result.database.timing.totalMs??0)/1000).toFixed(2)} s</p></details></>}
 <footer>Local analysis · CoinPoker timestamps preserved as recorded · Exact core calculations</footer></main>;}
createRoot(document.getElementById('root')!).render(<App/>);
