import {sha256} from '@noble/hashes/sha2.js';
import {scanLines,scanHands} from '../parser/scanner.ts';
import {readableChunks} from '../import/browser.ts';
import {processHand,canonicalContent,Deduplicator,type ProcessedHand} from '../import/core.ts';
import {calculateEV,type EquityCache} from '../equity/allInEV.ts';
import {buildSessions,type Session} from '../metrics/sessions.ts';
import {fact,query,type Fact,type Filters,type Database,defaults} from './data.ts';
let facts:Fact[]=[],sessions:Session[]=[],db:Database,ready=false,filters=defaults,request=0;
const send=(type:string,payload:unknown)=>postMessage({type,payload});
const hex=(bytes:Uint8Array)=>Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');
function compatible(q:Filters):Filters {return db?{...q,limits:q.limits.filter(v=>db.limits.includes(v)),positions:q.positions.filter(v=>db.positions.includes(v)),tables:q.tables.filter(v=>db.tables.includes(v)),players:db.players.includes(q.players)?q.players:''}:q;}
function reply(){if(db){filters=compatible(filters);send('result',{request,filters,result:query(facts,sessions,filters,db,ready)});}}
onmessage=async(event:MessageEvent<{type:string;file?:File;filters?:Filters;request?:number}>)=>{const m=event.data;if(m.type==='query'){filters=m.filters!;request=m.request!;reply();return;}if(m.type!=='import')return;try {const file=m.file!;if(!file.name.toLowerCase().endsWith('.txt'))throw Error('Choose a CoinPoker .txt file.');const start=performance.now(),hash=sha256.create(),dedup=new Deduplicator(),queue:{p:ProcessedHand;f:Fact}[]=[],cache:EquityCache=new Map();let bytes=0,parsed=0,duplicates=0,conflicts=0,errors=0,last=0;facts=[];ready=false;
 async function* chunks(){for await(const chunk of readableChunks(file.stream())){bytes+=chunk.length;hash.update(chunk);yield chunk;}}
 for await(const raw of scanHands(scanLines(chunks()))){parsed++;const p=processHand(raw,{equity:false});const accepted=dedup.accept(p.hand.handId,hex(sha256(new TextEncoder().encode(canonicalContent(raw)))),raw);if(accepted!=='insert'){if(accepted==='duplicate')duplicates++;else conflicts++;continue;}errors+=p.hand.diagnostics.filter(d=>d.severity==='error').length;const f=fact(p);facts.push(f);if(p.hand.gameType==='BombPot'||p.hero.logicalShowdown.value===true&&p.ledger.actions.some(a=>a.allIn))queue.push({p,f});else f.ev=calculateEV(p.hand,p.ledger,p.pots,p.hero,cache);if(performance.now()-last>160){send('progress',{stage:'Parsing & normalizing',parsed,percent:100*bytes/file.size});last=performance.now();await new Promise(r=>setTimeout(r,0));}}
 if(!facts.some(f=>/^\d+$/.test(f.hand.handId)))throw Error('No CoinPoker hands were found in this file.');facts.sort((a,b)=>(a.hand.startedAt?.ordinalSeconds??0)-(b.hand.startedAt?.ordinalSeconds??0)||a.hand.handId.localeCompare(b.hand.handId,undefined,{numeric:true}));sessions=buildSessions(facts.flatMap(f=>f.interval?[f.interval]:[]));const parseMs=performance.now()-start;db={filename:file.name,importedAt:new Date().toISOString(),parsed,unique:facts.length,duplicates,conflicts,errors,hash:hex(hash.digest()),start:facts[0]?.hand.startedAt?.dateKey??'',end:facts.at(-1)?.hand.startedAt?.dateKey??'',sessions:sessions.length,limits:[...new Set(facts.map(f=>f.hand.bigBlind.toString()))].sort((a,b)=>Number(a)-Number(b)),tables:[...new Set(facts.map(f=>f.hand.tableId))].sort(),positions:[...new Set(facts.map(f=>f.hero.position.value??'Unavailable'))],players:[...new Set(facts.map(f=>String(f.players)))].sort(),timing:{parseMs,firstDashboardMs:performance.now()-start}};
 filters={...filters,limits:filters.limits.filter(v=>db.limits.includes(v)),tables:filters.tables.filter(v=>db.tables.includes(v)),positions:filters.positions.filter(v=>db.positions.includes(v)),players:db.players.includes(filters.players)?filters.players:''};reply();send('basicReady',null);const evStart=performance.now();
 for(let i=0;i<queue.length;i++){const {p,f}=queue[i]!;f.ev=calculateEV(p.hand,p.ledger,p.pots,p.hero,cache);queue[i]=undefined as unknown as typeof queue[number];send('progress',{stage:'Calculating All-in EV',parsed:facts.length,percent:100*(i+1)/queue.length});await new Promise(r=>setTimeout(r,0));}db.timing.evMs=performance.now()-evStart;db.timing.totalMs=performance.now()-start;ready=true;reply();send('complete',null);
 }catch(e){send('error',e instanceof Error?e.message:'Worker import failed.');}};
